Update kubesec.yml

diff --git a/.github/workflows/kubesec.yml b/.github/workflows/kubesec.yml
--- a/.github/workflows/kubesec.yml
+++ b/.github/workflows/kubesec.yml
@@ -21,28 +21,29 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Run Kubesec scanner
-        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
+        uses: controlplaneio/kubesec-action@v2
         with:
           input: k8s/backend-deploy.yml
           format: json
           output: kubesec-results.sarif
 
+      - name: Validate SARIF output
+        run: |
+          if ! jq -e . kubesec-results.sarif > /dev/null 2>&1; then
+            echo "Invalid SARIF file"
+            exit 1
+          fi
+
       - name: Upload Kubesec scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: kubesec-results.sarif
-# # This workflow uses actions that are not certified by GitHub.
-# # They are provided by a third-party and are governed by
-# # separate terms of service, privacy policy, and support
-# # documentation.
-
 # name: Kubesec
 
 # on:
 #   push:
 #     branches: [ "DevOps" ]
 #   pull_request:
-#     # The branches below must be a subset of the branches above
 #     branches: [ "DevOps" ]
 #   schedule:
 #     - cron: '26 18 * * 4'
@@ -59,23 +60,15 @@ jobs:
 #       - name: Checkout code
 #         uses: actions/checkout@v4
 
-#       # - name: Run kubesec scanner
-#       #   uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
-#       #   with:
-#       #     input: k8s/backend-deploy.yml # specify configuration file to scan here
-#       #     format: template
-#       #     template: template/sarif.tpl
-#       #     output: kubesec-results.sarif
-#       #     exit-code: "0"
 #       - name: Run Kubesec scanner
-#         uses: controlplaneio/kubesec-action@v2
+#         uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
 #         with:
-#           input: "k8s/*.yaml"
+#           input: k8s/backend-deploy.yml
 #           format: json
 #           output: kubesec-results.sarif
-
 
 #       - name: Upload Kubesec scan results to GitHub Security tab
 #         uses: github/codeql-action/upload-sarif@v3
 #         with:
 #           sarif_file: kubesec-results.sarif
+
